### ISSUE TITLE
How to ensure email deliverability?

### ISSUE THREAD

**Issue by dentro-innovation** [useplunk/plunk#127]
Researching email automation tools, I came across this great open source project!

I think about self hosting it and using it for our (rather small) SaaS apps.

In the past we came across the problem that emails might not get delivered, due to a multitude of reasons - I'm no expert in this.

However, I learned that deliverability can be a tricky topic.

How to ensure emails reach the inbox when self-hosting plunk?

I intend to rent a Hetzner server and deploy plunk there for context.

**Comment by driaug** [comment]
Hi! When you self-host Plunk, your emails are still being sent through AWS SES so the server/service you deploy it on has no impact.

The most important part is domain reputation management. It is essentially credibility you build up for your domain by sending emails. If your emails do not bounce (Happens when you send to addresses that don't exist for example) or do not get reported as spam, your reputation goes up.

You have a lot of control over this. Making sure that when an email bounces or gets reported as spam that you do not send to that address again (Plunk does this for you), offer people easy ways to unsubscribe (Plunk does this for you), and in general just keeping an eye on the feedback you receive from your recipients.

**Comment by dentro-innovation** [comment]
Awesome thank you that makes a lot of sense!

Wasn't aware what kind of service AWS SES is.

I see there's a great guide on how to set up everything on AWS... but of course now I see that self-hosting is more difficult than just spinning up a docker container and that devs might prefer the hosted version!
