### ISSUE TITLE
Malformed MX record due to undefined AWS region

### ISSUE THREAD

**Issue by 0xi4o** [useplunk/plunk#73]
When verifying domains, the generated MX record value is missing the AWS region.

![Plunk-Dashboard-The-Open-Source-Email-Platform](https://github.com/user-attachments/assets/eb554a1c-b442-4cc3-b089-e5b8d62cd6ba)

I've set `AWS_REGION` to `ap-south-1`. The app is hosted on Railway.

From looking at the code, seems like Next.js reads the region from a `NEXT_PUBLIC_AWS_REGION` env variable but even after setting it and redeploying, the MX record is still missing the region. 

After copy-pasting the MX records, it looks like this:
![DNS-Records-herald-tools-i4o-Cloudflare](https://github.com/user-attachments/assets/226ba657-a9f5-4a3c-97a3-c486bb494877)

**Comment by driaug** [comment]
Aha! This is because that variable isn't being rewritten on deployment.

If you would want to fix it yourself, this is the script you are looking for: https://github.com/useplunk/plunk/blob/main/deployment/replace-variables.sh

We already do it for the APP_URI but should do it for `AWS_REGION` as well.

**Comment by raphaelm-gioa** [comment]
Hey there! Awesome package, literally insane work !

I think the problem here is also found when cron run (I also have the "undefined" issue in the region)
They run using API_URL and it seems to be the same issue (since Campaigns hang on queue, and to trigger them I am using the API call to /tasks)
Also, you mention APP_URI in the comment above but its PLUNK_API_URI that is being replaced, or am I missing something
Will gladly open a PR for that but I'm not sure of the variables needed to be changed ! 😊 
PS: I am also not sure why we need the replace-variables script ! In a self-hosted environment

**Comment by driaug** [comment]
Closed by #118
